version: 2
jobs:
    build:
      docker:
      - image: $BUILD_CONTAINER_IMAGE
        auth:
          username: _json_key
          password: $TRIGGERMAIL_GCR_AUTH
      working_directory: /home/circleci/go/src/github.com/TriggerMail/<repo>
      steps:
        - checkout
        - run:
            name: Export PATH for Deployment
            command: |
              /home/circleci/devenv/bluecore activate >> $BASH_ENV
              echo "GOPATH=/home/circleci/go" >> $BASH_ENV
        - run: 
            name: Find formatting issues
            command: go vet ./...
        - run:
            name: Run tests
            # Runs each test 10 times to try to avoid flaky tests or depending on map ordering
            command: go test -race -count=10 ./...
        - run:
            name: Check code is formatted with gofmt
            command: |
              go fmt ./...
              CHANGED=$(git status --porcelain --untracked-files=no)
              if [ -n "${CHANGED}" ]; then
                  echo "ERROR Go files must be formatted with go fmt; Format these files:" > /dev/stderr
                  echo "$CHANGED" > /dev/stderr
                  exit 10
              fi
        - run:
            name: Upload image
            command: |
              if [ $CIRCLE_BRANCH == "master" ]; then
                echo $TRIGGERMAIL_GCR_AUTH > ${HOME}/gcloud-service-key.json
                gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
                bluecore cloudbuild . --config cloudbuilder.yaml --service-name customers --tag $CIRCLE_SHA1 --gcloud-key-path $HOME/gcloud-service-key.json
              fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: build-global
