version: 2
jobs:
    build:
      docker:
      - image: $BUILD_CONTAINER_IMAGE
        auth:
          username: _json_key
          # This was a key generated in gcloud's bluecore-qa IAM console for circle-ci-image-retrieval@bluecore-qa.iam.gserviceaccount.com
          # this service-account has read access to bluecore-qa: artifacts.bluecore-qa.appspot.com where images are stored.
          password: $GCR_TM_AUTH
      working_directory: /home/circleci/go/src/github.com/TriggerMail/<repo>
      steps:
        - checkout
        - run:
            name: Export PATH for Deployment
            command: |
              /home/circleci/devenv/bluecore activate >> $BASH_ENV
              echo "GOPATH=/home/circleci/go" >> $BASH_ENV
        - run: 
            name: Find formatting issues
            command: go vet ./...
        - run:
            name: Run tests
            # Runs each test 10 times to try to avoid flaky tests or depending on map ordering
            command: go test -race -count=10 ./...
        - run: 
            name: Find formatting issues
            command: diff -u <(echo -n) <(gofmt -d ./...)
        - run:
            name: Upload image
            command: |
              if [ $CIRCLE_BRANCH == "master" ]; then
                echo $GCR_TM_AUTH > ${HOME}/gcloud-service-key.json
                gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
                bluecore cloudbuild . --config cloudbuilder.yaml --service-name customers --tag $CIRCLE_SHA1 --gcloud-key-path $HOME/gcloud-service-key.json
              fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: build-global